api_login_check:
  path:
    en: /login_check
    de: /login_check

createUser:
    path:
      en: /user
      de: /benutzer
    controller: App\Infrastructure\Controller\RegisterUserController:handleRequest
    methods: [post]

createJob:
  path:
    en: /job
    de: /arbeit
  controller: App\Infrastructure\Controller\CreateJobController:handleRequest
  methods: [post]

updateJob:
  path:
    en: /job
    de: /arbeit
  controller: App\Infrastructure\Controller\UpdateJobController:handleRequest
  methods: [put]

getJob:
  path:
    en: /job/{uuid}
    de: /arbeit/{uuid}
  controller: App\Infrastructure\Controller\GetJobController:handleRequest
  methods: [get]
  requirements:
    uuid: !php/const App\Domain\ValueObject\Uuid::UUID_PATTERN

deleteJob:
  path:
    en: /job/{uuid}
    de: /arbeit/{uuid}
  controller: App\Infrastructure\Controller\DeleteJobController:handleRequest
  methods: [delete]
  requirements:
    uuid: !php/const App\Domain\ValueObject\Uuid::UUID_PATTERN

home:
  path:
    en: /{wildcard}
    de: /{wildcard}
  requirements:
    wildcard: .*
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    # the path of the template to render
    template:  'default/index.html.twig'

    # special options defined by Symfony to set the page cache
    maxAge:    86400
    sharedAge: 86400